---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "optimizer.confName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "optimizer-chart.labels" . | nindent 4 }}
data:
  cluster-optimizer.yaml: |-
    server:
      port: 7070
    engine:
      maxQueryDuration: 1h
    optconf:
      dataSource:
        name: "{{ include "optimizedb.conf.datasource" .}}"
        maxOpenConns: {{ include "optimizedb.conf.datasource.maxOpenConns" . }}
    optdata:
      dataSource:
        name: "{{ include "optimizedb.data.datasource" .}}"
        maxOpenConns: {{ include "optimizedb.data.datasource.maxOpenConns" . }}
    {{- with .Values.optimizedb.user }}
    user:
      dataSource:
        name: "{{ include "optimizedb.user.datasource" .}}"
        maxOpenConns: {{ include "optimizedb.user.datasource.maxOpenConns" . }}
    {{- end }}
    {{- with .Values.optimize }}
    optimize:
    {{- toYaml . | nindent 6 }}
    {{- end }}   
    {{- with .Values.sms }}
    sms:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.email }}
    email:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.license }}
    license:
    {{- toYaml . | nindent 6 }}
    {{- end }}