---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "optimizer.svcName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "optimizer-chart.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    {{- include "optimizer-chart.selectorLabels" . | nindent 4 }}
  type: ClusterIP