{{- if .Values.optimizedb.create }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "optimizerDB.pvcName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    meta.helm.sh/release-name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/managed-by: Helm
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "2Gi" .Values.optimizedb.size }}
{{- end }}