{{- if .Values.optimizedb.create }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "optimizerDB.svcName" . }}
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    {{- include "optimizedb.selectorLabels" . | nindent 4 }}
  type: ClusterIP
{{- end }}